### ISSUE TITLE
I'm unable to run concourse-tutorial after successful deploy

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-community/bosh-init-concourse#5]
When running the example from: https://github.com/drnic/concourse-tutorial/tree/master/01_task_hello_world I'm encountering:
![concourse issue](https://cloud.githubusercontent.com/assets/380697/7230162/822abffa-e76b-11e4-942f-5500dda101ad.png)

**Comment by drnic** [comment]
@rkoster did you set `$ATC_URL` first? e.g. `export ATC_URL=http://54.163.32.37:8080`

**Comment by rkoster** [comment]
yes otherwise I don't think there would be output in the GUI

**Comment by drnic** [comment]
Yeah I think the error is different (long pauses). Just checking. Will redeploy later.
